[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasiser/vim-code-dark'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'sjl/gundo.vim'
